stages:
  - build
  - deploy

mattermost_build:
  stage: build
  tags:
    - podman
  image: nexus.almaz-rpe.ru/podman/stable
  only:
    - deploy
  script:
    - echo "BUILDING MATTERMOST IMAGE.."
    - podman image build --file ./Containerfile --tag mm-build
    - podman cp mm-build:/mattermost/server/dist/mattermost*.tar.gz ./mattermost.tar.gz
  artifacts:
    paths:
      - mattermost.tar.gz
    expire_in: 1 week

mattermost_deploy:
  stage: deploy
  tags:
    - podman
  image: nexus.almaz-rpe.ru/podman/stable
  only:
    - deploy
  script:
    - chmod og= $ID_ED25519
    - echo "COPYING THE TARBALL.."
    - scp -i $ID_ED25519 -o StrictHostKeyChecking=no ./mattermost.tar.gz root@$DEPLOY_HOST:/root
    - echo "BACKING UP THE MATTERMOST WORKDIR.."
    - >
      ssh -i $ID_ED25519 -o StrictHostKeyChecking=no root@$DEPLOY_HOST
      cp -ra /opt/mattermost/ ~/mattermost-back-$(date +'%F-%H-%M')
    - echo "BACKING UP THE MATTERMOST DB.."
    - >
      ssh -i $ID_ED25519 -o StrictHostKeyChecking=no root@$DEPLOY_HOST
      pg_dump -U mmuser -Fc mattermost > ~/mattermost.sql
    - echo "UNPACKING THE TARBALL.."
    - >
      ssh -i $ID_ED25519 -o StrictHostKeyChecking=no root@$DEPLOY_HOST
      tar -xf mattermost.tar.gz --transform='s,^[^/]\+,\0-upgrade,'
    - echo "STOPPING THE MATTERMOST SERVICE.."
    - >
      ssh -i $ID_ED25519 -o StrictHostKeyChecking=no root@$DEPLOY_HOST
      systemctl stop mattermost.service
    - echo "REMOVING OLD FILES.."
    - >
      ssh -i $ID_ED25519 -o StrictHostKeyChecking=no root@$DEPLOY_HOST
      find /opt/mattermost/ /opt/mattermost/client/ -mindepth 1 -maxdepth 1 \! \( -type d \( -path /opt/mattermost/client -o -path /opt/mattermost/client/plugins -o -path /opt/mattermost/config -o -path /opt/mattermost/logs -o -path /opt/mattermost/plugins -o -path /opt/mattermost/data -o -path /opt/mattermost/cert \) -prune \) | sort | sudo xargs rm -r
    - echo "COPYING THE UNPACKED FILES.."
    - >
      ssh -i $ID_ED25519 -o StrictHostKeyChecking=no root@$DEPLOY_HOST
      cp -an ~/mattermost-upgrade/. /opt/mattermost/
    - echo "CHANGING THE OWNER && GROUP OF THE MATTERMOST WORKDIR.."
    - >
      ssh -i $ID_ED25519 -o StrictHostKeyChecking=no root@$DEPLOY_HOST
      chown -R mattermost:mattermost /opt/mattermost/
    - echo "STARTING THE MATTERMOST SERVICE.."
    - >
      ssh -i $ID_ED25519 -o StrictHostKeyChecking=no root@$DEPLOY_HOST
      systemctl start mattermost.service
