FROM nexus.almaz-rpe.ru/mattermost/mattermost-build-server:1.24.11

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN mkdir /work

WORKDIR /work

#RUN git clone https://github.com/mattermost/mattermost && \
#      sed -i 's/200/2000/' ./mattermost/server/channels/app/limits.go && \
#      sed -i 's/250/2500/' ./mattermost/server/channels/app/limits.go

#ENV NVM_VERSION=v0.40.3
ENV NVM_DIR=/root/.nvm

#RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash

RUN source $NVM_DIR/nvm.sh && \
      nvm --version

#RUN source $NVM_DIR/nvm.sh && \
#      cd ./mattermost/webapp && \
#      nvm install && \
#      cd ../server && \
#      make build && \
#      make package
